name: CI

on:
  push:
    branches: [main]

  pull_request: # run on all PRs

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: ".node-version"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: nub ci --ignore-scripts

      - name: Lint JS-like files
        run: npmx eslint .  --max-warnings 0

  typecheck:
    name: Typecheck

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: ".node-version"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: nub ci --ignore-scripts

      - name: Check types
        run: npm run check
